### ISSUE TITLE
Server install

### ISSUE THREAD

**Issue by hymaxo** [saurass/Zombie-DDoS#3]
The server is not working correctly. When connecting a bot to the server, the number of bots does not change. When the bot is connected to the demo version, everything works.

**Comment by Tina-1300** [comment]
j'ai le même problème mais bon, ses deja pas mal ça marche j'ai vue vlaa les paquet réseaux passer par wiershark

**Comment by Tina-1300** [comment]
enfête le programme envoi une requet au server pour lui passer un id mais il n'est pas executer tout les example 5 minutes ou plus donc ça dois être ça après l'appli ne ce souvient plus mais je pance que si on fait cela genre ça devrait allez nan
